name: Mini CI/CD Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Ambil Kode
      uses: actions/checkout@v4       # <-- Sudah diupdate ke v4

    - name: Setup Python
      uses: actions/setup-python@v5   # <-- Sudah diupdate ke v5
      with:
        python-version: '3.9'

    - name: Jalankan Test
      run: python test_app.py

    - name: Upload Laporan
      if: always()
      uses: actions/upload-artifact@v4  # <-- INI YANG BIKIN ERROR TADI (Sekarang v4)
      with:
        name: laporan-pengujian
        path: test-report.txt
